# Generated by Django 4.0.4 on 2022-04-15 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Компания', max_length=24)),
                ('location', models.CharField(default='Москва', max_length=16)),
                ('logo', models.URLField(default='https://place-hold.it/100x60')),
                ('description', models.TextField(default='Информация')),
                ('employee_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='backend', max_length=8)),
                ('title', models.CharField(default='Бэкэнд', max_length=8)),
                ('picture', models.URLField(default='https://place-hold.it/100x60')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Джуниор', max_length=64)),
                ('skills', models.TextField(blank=True)),
                ('description', models.TextField(default='Описание')),
                ('salary_min', models.IntegerField(null=True)),
                ('salary_max', models.IntegerField(null=True)),
                ('published_at', models.DateField(auto_now=True)),
                ('company',
                 models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE,
                                   related_name='vacancies',
                                   to='base_here.company')),
                ('specialty',
                 models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE,
                                   related_name='vacancies',
                                   to='base_here.specialty')),
            ],
        ),
    ]
