# Generated by Django 4.0.4 on 2022-04-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base_here', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.CharField(default='backend', max_length=24),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='title',
            field=models.CharField(default='Бэкэнд', max_length=24),
        ),
    ]
